batch_size : 512
num_batch : 60
# num_batch : 4

precision: high  # high | medium, 

# scaffold : null # fill the SMILES of the scaffold here, enabled when not null

# scaffold : "C1C=CNC2=CC=CC=C21"  # 1,3-Dimethylquinolin-4(1H)-one
# scaffold : "CC1=CN(C2=CC=CC=C2C1=O)C"  # 1,4-Dihydroquinoline
# scaffold : "C1=CC(=CC(=C1)N)C(F)(F)F"  # 3-(Trifluoromethyl)aniline
# scaffold : "C1=NN(C2=C1N=C(NC2=O)C3=C(C=CC(=C3)S(=O)(=O)N4CCN(CC4)))C"  # Sildenafil

num_nodes: null # fix the node per graph in coarse sample stage

coarse_cfg: ../configs/guacamol_exp/coarse.yaml
refine_cfg: ../configs/guacamol_exp/refine.yaml

coarse_ckpt: ../checkpoints/guacamol/coarse_last.ckpt
refine_ckpt: ../checkpoints/guacamol/refine_last.ckpt

skip_t : 1
devices : 0
save_graphs : True   # save the one-hot output tensor
enable_progress_bar : True
